#!/bin/sh
#
#	Creation of the temperatures database
#	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#	@(#)	[MB] ee_mk_base	Version 1.2 du 20/02/10 - 
#

MYSQL='mysql' 

#	Read parameters file
#	~~~~~~~~~~~~~~~~~~~~
. ./param_temperature

trap 'stty echo' 0 1 2 3 15

stty -echo
/bin/echo -n "Enter database root password : "
read PASS
export PASS
echo
stty echo


if [ "$1" != "" ]
then
	DATABASE="$1"
fi

echo "Database creation ..."
"$MYSQL" -u root --password="$PASS" << EOF
	CREATE DATABASE $DATABASE;
EOF
echo


echo "Creation of the 'temp' table ..."
"$MYSQL" -u root --password="$PASS" << EOF
	use $DATABASE;

	CREATE TABLE temp (
		nodename            VARCHAR(32)             NOT NULL,
		ts                  TIMESTAMP               DEFAULT 0,
		id 				INTEGER                 AUTO_INCREMENT,
		temp_source         VARCHAR(256)            NOT NULL,
		temp_value          INTEGER,

		PRIMARY KEY(id)
	) ENGINE InnoDB;
EOF

"$MYSQL" -t -u root --password="$PASS" << EOF
	use $DATABASE;

	desc temp;
EOF
echo
