#!/bin/bash
#
#	@(#)	[MB] aj_ls_by_day	Version 1.1 du 16/05/08 - 
#

hl_opts()
{
	for d in {0..6}
	do
		case $d in
			0)	color=3c
				;;

			1)	color=2g
				;;

			2)	color=3y
				;;

			3)	color=1y
				;;

			4)	color=3r
				;;

			5)	color=1r
				;;

			6)	color=1m
				;;

			*)	color=n
				;;
		esac

		HL_COL="-$color"
		day=$(date '+%b %2e' -d "@$(echo "$(date '+%s') 24 3600 * $d * - p" | dc)")
		HL_RE="$day ..:.. .+"
		echo -n "$HL_COL" "'$HL_RE' "
	done

	 echo " "

}

/bin/ls -l "$@" | eval hl -e "$(hl_opts)"
